### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by Chenmo1212** [XOS/niRvana#2]
您好，想问一下，使用主题出现这种报错应该如何解决啊？

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/blog.domin.cn/wp-content/themes/niRvana-Crack/pandastudio_framework/assets/template/posttype_json.php on line 2

**Comment by XOS** [comment]
最高支持 PHP7.3

**Comment by Chenmo1212** [comment]
您的php版本是多少呀？我的是PHP 7.2.33 (cli) ，可是还是不行呀

**Comment by XOS** [comment]
7.3
